defaults: &defaults
  n_samples: 100

pipeline:
  - step: "Generation with GPT3 (0-shot)"
    script: "main.py"
    args:
      - "generate"
    params:
      <<: *defaults
      output: "generated/GPT3 Zero-shot.csv"
      model: "GPT3"
      strategy: "zero-shot"

  - step: "Generation with microsoft/Phi-3.5 (0-shot)"
    script: "main.py"
    args:
      - "generate"
    params:
      <<: *defaults
      output: "generated/microsoft-Phi-3.5 Zero-shot.csv"
      model: "microsoft/Phi-3.5"
      strategy: "zero-shot"

  - step: "Generation with Qwen/Qwen2.5-3B-Instruct-GPTQ-Int8 (0-shot)"
    script: "main.py"
    args:
      - "generate"
    params:
      <<: *defaults
      output: "generated/Qwen2.5-3B-Instruct-GPTQ-Int8 Zero-shot.csv"
      model: "Qwen/Qwen2.5-3B-Instruct-GPTQ-Int8"
      strategy: "zero-shot"

  - step: "Generation with GPT3 (few-shot)"
    script: "main.py"
    args:
      - "generate"
    params:
      <<: *defaults
      output: "generated/GPT3 Few-shot.csv"
      model: "GPT3"
      strategy: "few-shot"

  - step: "Generation with microsoft/Phi-3.5 (few-shot)"
    script: "main.py"
    args:
      - "generate"
    params:
      <<: *defaults
      output: "generated/microsoft-Phi-3.5 Few-shot.csv"
      model: "microsoft/Phi-3.5"
      strategy: "few-shot"

  - step: "Generation with Qwen/Qwen2.5-3B-Instruct-GPTQ-Int8 (few-shot)"
    script: "main.py"
    args:
      - "generate"
    params:
      <<: *defaults
      output: "generated/Qwen2.5-3B-Instruct-GPTQ-Int8 Few-shot.csv"
      model: "Qwen/Qwen2.5-3B-Instruct-GPTQ-Int8"
      strategy: "few-shot"

  - step: "Evaluation"
    script: "main.py"
    args:
      - "evaluate"
    params:
      dir: "generated"
